# Generated by Django 6.0.3 on 2026-03-20 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('endereço', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sorvete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sorvete', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField(verbose_name='Data do evento')),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=500)),
                ('disponibilidade', models.BooleanField(default=False)),
                ('id_carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.carrinho')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.reserva')),
                ('id_sorvete', models.ManyToManyField(related_name='sorvetes', to='aluguel.sorvete')),
            ],
        ),
    ]
