# Generated by Django 6.0.3 on 2026-03-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_cliente_sorvete_reserva_reservaproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorvete',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='sabores/'),
        ),
    ]
