# Generated by Django 6.0.3 on 2026-04-03 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0004_alter_reserva_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
