# Generated by Django 6.0.3 on 2026-04-07 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0005_rename_endereço_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaproduto',
            name='quantidade_escolhida',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='valor_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='reservaproduto',
            name='id_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='aluguel.reserva'),
        ),
        migrations.RemoveField(
            model_name='reservaproduto',
            name='id_sorvete',
        ),
        migrations.AddField(
            model_name='reservaproduto',
            name='id_sorvete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aluguel.sorvete'),
        ),
    ]
