# Generated by Django 6.0.3 on 2026-04-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0006_reservaproduto_quantidade_escolhida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
