# Generated by Django 6.0.3 on 2026-04-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0007_alter_reserva_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorvete',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
