# Generated by Django 6.0.3 on 2026-04-13 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0008_sorvete_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id_carrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluguel.carrinho'),
        ),
    ]
