# Generated by Django 6.0.3 on 2026-05-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0009_alter_reserva_id_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
